version: '3'
services:
  postgres:
    image: postgres:13
    restart: always
    env_file:
      - .env
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin2
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - postgres
  
  scheduler:
    build: .
    command: scheduler
    restart: on-failure
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./scripts:/opt/airflow/scripts

  webserver:
    build: .
    entrypoint: ./scripts/entrypoint.sh
    restart: on-failure
    command: webserver
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - pgadmin
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./scripts:/opt/airflow/scripts
    env_file:
      - .env

volumes:
  postgres-db-volume: